import { useEffect, useState } from 'react';
import { useParams, useLocation } from 'react-router-dom';
import { motion } from 'motion/react';
import { Star, Hotel, Compass, ExternalLink } from 'lucide-react';
import axios from 'axios';
import { useAuth } from '../context/AuthContext';

export default function TripResults() {
  const { id } = useParams();
  const locationState = useLocation();
  const [trip, setTrip] = useState(locationState.state?.plan || null);
  const [tripDetails, setTripDetails] = useState(null);
  const { token } = useAuth();

  useEffect(() => {
    if (!trip && id) {
      axios.get(`/api/trips/${id}`, {
        headers: { Authorization: `Bearer ${token}` }
      }).then(res => {
        setTrip(res.data.itinerary);
        setTripDetails(res.data);
      });
    }
  }, [id, trip, token]);

  if (!trip) return <div className="flex items-center justify-center min-h-[60vh]">Loading...</div>;

  const openInMaps = (query) => {
    window.open(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`, '_blank');
  };

  return (
    <div className="max-w-6xl mx-auto px-4 py-12">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="mb-12"
      >
        <h1 className="text-4xl font-bold mb-2 tracking-tight">Your Custom Itinerary</h1>
        <p className="text-gray-600">
          {tripDetails ? `Trip to ${tripDetails.location} for ${tripDetails.days} days` : 'Generated by AI'}
        </p>
      </motion.div>

      {/* Hotels Section */}
      <section className="mb-16">
        <div className="flex items-center gap-2 mb-6">
          <Hotel className="text-gray-400" />
          <h2 className="text-2xl font-bold uppercase tracking-widest text-gray-500 text-sm">Recommended Hotels</h2>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {trip.hotels.map((hotel, idx) => (
            <motion.div
              key={idx}
              whileHover={{ y: -5 }}
              className="bg-white rounded-2xl shadow-lg border border-black/5 overflow-hidden group cursor-pointer"
              onClick={() => openInMaps(hotel.name)}
            >
              <div className="h-48 bg-gray-100 relative">
                <img 
                  src={`https://picsum.photos/seed/${hotel.name}/400/300`} 
                  alt={hotel.name}
                  className="w-full h-full object-cover"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute top-4 right-4 bg-white/90 backdrop-blur px-2 py-1 rounded-lg flex items-center gap-1 text-sm font-bold">
                  <Star size={14} className="text-yellow-500 fill-yellow-500" />
                  {hotel.rating}
                </div>
              </div>
              <div className="p-6">
                <h3 className="font-bold text-xl mb-1 group-hover:underline flex items-center justify-between">
                  {hotel.name}
                  <ExternalLink size={16} className="opacity-0 group-hover:opacity-100 transition-opacity" />
                </h3>
                <p className="text-gray-500 text-sm mb-4 line-clamp-2">{hotel.description}</p>
                <div className="flex items-center justify-between mt-auto">
                  <span className="text-lg font-bold">{hotel.price}</span>
                  <span className="text-xs uppercase tracking-widest font-bold text-gray-400">Per Night</span>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Itinerary Section */}
      <section>
        <div className="flex items-center gap-2 mb-8">
          <Compass className="text-gray-400" />
          <h2 className="text-2xl font-bold uppercase tracking-widest text-gray-500 text-sm">Day-by-Day Plan</h2>
        </div>
        <div className="space-y-12">
          {trip.itinerary.map((day, idx) => (
            <div key={idx} className="relative pl-8 border-l-2 border-gray-100">
              <div className="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-black border-4 border-white shadow-sm" />
              <div className="mb-6">
                <h3 className="text-3xl font-bold mb-1">Day {day.day}</h3>
                <p className="text-gray-400 font-medium italic">{day.theme}</p>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {day.activities.map((spot, sIdx) => (
                  <motion.div
                    key={sIdx}
                    whileHover={{ x: 5 }}
                    className="bg-gray-50 rounded-2xl p-6 flex gap-4 cursor-pointer group"
                    onClick={() => openInMaps(spot.spotName)}
                  >
                    <div className="w-24 h-24 rounded-xl bg-white flex-shrink-0 overflow-hidden border border-black/5">
                       <img 
                        src={`https://picsum.photos/seed/${spot.spotName}/200/200`} 
                        alt={spot.spotName}
                        className="w-full h-full object-cover"
                        referrerPolicy="no-referrer"
                      />
                    </div>
                    <div>
                      <h4 className="font-bold text-lg group-hover:underline flex items-center gap-2">
                        {spot.spotName}
                        <ExternalLink size={14} className="opacity-0 group-hover:opacity-100" />
                      </h4>
                      <p className="text-gray-600 text-sm mb-2 line-clamp-2">{spot.description}</p>
                      <div className="flex items-center gap-4 text-xs font-bold uppercase tracking-wider text-gray-400">
                        <span className="flex items-center gap-1">
                          <Star size={12} className="text-yellow-500 fill-yellow-500" />
                          {spot.rating}
                        </span>
                        <span>Best: {spot.bestTime}</span>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
